<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uim"
    nsURI="http://nakeduml.org/uimetamodel/1.0" nsPrefix="uim">
  <eClassifiers xsi:type="ecore:EClass" name="UIMForm" abstract="true" eSuperTypes="#//UserInteractionElement">
    <eOperations name="getFolder" lowerBound="1" eType="#//AbstractFormFolder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="panel" eType="#//FormPanel"
        containment="true" eOpposite="#//FormPanel/form"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserInteractionModel" eSuperTypes="#//AbstractFolder #//UmlReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="umlModel" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="securityOnVisibility" eType="#//ModelSecurityConstraint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="secuirytOnEditability"
        eType="#//ModelSecurityConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractFormFolder" abstract="true"
      eSuperTypes="#//AbstractFolder">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//AbstractFolder"
        eOpposite="#//AbstractFolder/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="securityOnVisibility" eType="#//ChildSecurityConstraint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="securityOnEditability"
        eType="#//ChildSecurityConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractFolder" abstract="true" eSuperTypes="#//UserInteractionElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//AbstractFormFolder" containment="true" eOpposite="#//AbstractFormFolder/parent">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="wildcards" value=""/>
        <details key="name" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIMField" eSuperTypes="#//UIMComponent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A User Field is an abstract superclass for all fields a user can view and/or update on a form, typically represented as some kind of input/output form field."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="control" lowerBound="1"
        eType="#//UIMControl" containment="true" eOpposite="#//UIMControl/field"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="controlKind" eType="#//ControlKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelWidth" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Integer"
        defaultValueLiteral="200"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="binding" lowerBound="1"
        eType="#//FieldBinding" containment="true" eOpposite="#//FieldBinding/field"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="securityOnEditability"
        eType="#//ChildSecurityConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIMNavigation" abstract="true" eSuperTypes="#//UIMComponent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract superclass for elements that can be navigated to, typically by means of a menu item"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIMPanel" eSuperTypes="#//UIMContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassForm" eSuperTypes="#//UIMForm #//UmlReference">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="kind" value="mixed"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A ClassForm gives the user access to all the attributes and operations of ANY of the following types of classes:&#xD;&#xA;1. OrgUNit&#xD;&#xA;2. Role&#xD;&#xA;3. Normal Entity&#xD;&#xA;4. Process&#xD;&#xA;5. StateMachine"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="folder" lowerBound="1"
        eType="#//OperationContainingFolder" eOpposite="#//OperationContainingFolder/classForm"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateForm" eSuperTypes="#//UIMForm #//UmlReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="folder" lowerBound="1"
        eType="#//StateMachineFolder" eOpposite="#//StateMachineFolder/stateForms"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelSecurityConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredRoles" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiresGroupOwnership"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiresOwnership" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationInvocationForm" eSuperTypes="#//UIMForm #//UmlReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="folder" lowerBound="1"
        eType="#//OperationContainingFolder" eOpposite="#//OperationContainingFolder/operationInvocationForms"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIMComponent" abstract="true" eSuperTypes="#//UserInteractionElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="securityOnVisibility" eType="#//ChildSecurityConstraint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//UIMContainer"
        eOpposite="#//UIMContainer/children"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserInteractionElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationAction" eSuperTypes="#//UIMAction #//UmlReference">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An operation action is typically represented as a button and executes a parameterless operation. Most often used to transition in statemachines. It is made available as a single-click button action which allows the user to execute the operation without navigating to an input form, as would be the case with a OperationNavigation"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationToOperation" eSuperTypes="#//UIMNavigation #//UmlReference">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An operationNavigation is typically rendered as a menu item of some sort, and takes the user to an operationUserInteraction"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toForm" eType="#//OperationInvocationForm"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActionKind">
    <eLiterals name="update"/>
    <eLiterals name="delete" value="1"/>
    <eLiterals name="back" value="2"/>
    <eLiterals name="executeOperation" value="3"/>
    <eLiterals name="postponeTask" value="4" literal="postponeTask"/>
    <eLiterals name="completeTask" value="5"/>
    <eLiterals name="returnTask" value="6" literal="returnTask"/>
    <eLiterals name="create" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuiltInAction" eSuperTypes="#//UIMAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ActionKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIMControl">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="#//UIMField"
        eOpposite="#//UIMField/control"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ControlKind">
    <eLiterals name="datePopup"/>
    <eLiterals name="dropdown" value="1"/>
    <eLiterals name="text" value="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Displays a single line text input field"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="textArea" value="4">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Displays a multiline text area"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="singleSelectListBox" value="5"/>
    <eLiterals name="checkBox" value="7"/>
    <eLiterals name="numberScroller" value="9"/>
    <eLiterals name="singleSelectTreeView" value="8"/>
    <eLiterals name="multiSelectTreeView" value="10"/>
    <eLiterals name="multiSelectListBox" value="11"/>
    <eLiterals name="singleSelectPopupSearch" value="13"/>
    <eLiterals name="multiSelectPopupSearch" value="6">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Displays a dialog box that allows the user to search for matches and select multiple entries"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="toggleButton" value="12"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationToEntity" eSuperTypes="#//UIMNavigation #//UmlReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toForm" eType="#//ClassForm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="binding" eType="#//NavigationBinding"
        containment="true" eOpposite="#//NavigationBinding/navigation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransitionAction" eSuperTypes="#//UIMAction #//UmlReference">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A slightly less form approach is to allow the user to select which transition to take on submitting the form, in stead of letting the execution of an event cause the transition"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Transition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationTaskForm" eSuperTypes="#//UIMForm #//UmlReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="folder" lowerBound="1"
        eType="#//EntityFolder" eOpposite="#//EntityFolder/operationTaskForms"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionTaskForm" eSuperTypes="#//UIMForm #//UmlReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//OpaqueAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="folder" eType="#//ActivityFolder"
        eOpposite="#//ActivityFolder/actionTaskForms"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIMAction" abstract="true" eSuperTypes="#//UIMComponent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A User Action is an abstract superclass for all actions a user can take on a form, typically represented as a button."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChildSecurityConstraint" eSuperTypes="#//ModelSecurityConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inheritFromParent" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIMGridLayout" eSuperTypes="#//UIMLayout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfColumns" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Integer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIMDataTable" eSuperTypes="#//MasterComponent #//UIMContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binding" eType="#//TableBinding"
        containment="true" eOpposite="#//TableBinding/table"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIMBinding" abstract="true" eSuperTypes="#//UmlReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//PropertyRef"
        containment="true" eOpposite="#//PropertyRef/binding"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//TypedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyRef" eSuperTypes="#//UmlReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binding" eType="#//UIMBinding"
        eOpposite="#//UIMBinding/next"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous" eType="#//PropertyRef"
        eOpposite="#//PropertyRef/next"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//PropertyRef"
        containment="true" eOpposite="#//PropertyRef/previous"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIMDataColumn" eSuperTypes="#//UIMPanel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Integer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableBinding" eSuperTypes="#//UIMBinding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" lowerBound="1" eType="#//UIMDataTable"
        eOpposite="#//UIMDataTable/binding"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldBinding" eSuperTypes="#//UIMBinding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="#//UIMField"
        eOpposite="#//UIMField/binding"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FormPanel" eSuperTypes="#//UIMContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="form" eType="#//UIMForm"
        eOpposite="#//UIMForm/panel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateMachineFolder" eSuperTypes="#//OperationContainingFolder #//UmlReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateForms" upperBound="-1"
        eType="#//StateForm" containment="true" eOpposite="#//StateForm/folder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachine" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//StateMachine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityFolder" eSuperTypes="#//OperationContainingFolder #//UmlReference">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Could be any type of entity - OrgUnit, Role, Entity, etc."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationTaskForms" upperBound="-1"
        eType="#//OperationTaskForm" containment="true" eOpposite="#//OperationTaskForm/folder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityFolder" eSuperTypes="#//AbstractFormFolder #//UmlReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionTaskForms" upperBound="-1"
        eType="#//ActionTaskForm" containment="true" eOpposite="#//ActionTaskForm/folder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Activity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationContainingFolder" abstract="true"
      eSuperTypes="#//AbstractFormFolder">
    <eOperations name="getRepresentedClass" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationInvocationForms"
        upperBound="-1" eType="#//OperationInvocationForm" containment="true" eOpposite="#//OperationInvocationForm/folder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classForm" upperBound="-1"
        eType="#//ClassForm" containment="true" eOpposite="#//ClassForm/folder"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationBinding" eSuperTypes="#//UIMBinding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="navigation" lowerBound="1"
        eType="#//NavigationToEntity" eOpposite="#//NavigationToEntity/binding"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DetailPanel" eSuperTypes="#//UIMPanel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="masterComponent" eType="#//MasterComponent"
        eOpposite="#//MasterComponent/detailPanels"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageFolder" eSuperTypes="#//AbstractFormFolder #//UmlReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="umlPackage" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIMTabPanel" eSuperTypes="#//UIMContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activeTabIndex" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Integer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIMTab" eSuperTypes="#//UIMPanel"/>
  <eClassifiers xsi:type="ecore:EClass" name="UIMCheckBox" eSuperTypes="#//UIMControl"/>
  <eClassifiers xsi:type="ecore:EClass" name="UIMLookup" eSuperTypes="#//UIMControl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lookupSource" eType="#//LookupBinding"
        containment="true" eOpposite="#//LookupBinding/lookup"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LookupBinding" eSuperTypes="#//UIMBinding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lookup" eType="#//UIMLookup"
        eOpposite="#//UIMLookup/lookupSource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIMText" eSuperTypes="#//UIMControl"/>
  <eClassifiers xsi:type="ecore:EClass" name="UIMTextArea" eSuperTypes="#//UIMControl">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rows" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Integer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIMDropdown" eSuperTypes="#//UIMLookup"/>
  <eClassifiers xsi:type="ecore:EClass" name="UIMDatePopup" eSuperTypes="#//UIMControl"/>
  <eClassifiers xsi:type="ecore:EClass" name="UIMSingleSelectListBox" eSuperTypes="#//UIMLookup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rows" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Integer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIMContainer" eSuperTypes="#//UIMComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="securityOnEditability"
        eType="#//ChildSecurityConstraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//UIMComponent" containment="true" eOpposite="#//UIMComponent/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIMSingleSelectTreeView" eSuperTypes="#//MasterComponent #//UIMLookup"/>
  <eClassifiers xsi:type="ecore:EClass" name="MasterComponent" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="detailPanels" upperBound="-1"
        eType="#//DetailPanel" eOpposite="#//DetailPanel/masterComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIMLayout" eSuperTypes="#//UIMContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="UIMToolbarLayout" eSuperTypes="#//UIMLayout"/>
  <eClassifiers xsi:type="ecore:EClass" name="UIMBorderLayout" eSuperTypes="#//UIMLayout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horizontal" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIMXYLayout" eSuperTypes="#//UIMLayout"/>
  <eClassifiers xsi:type="ecore:EClass" name="UIMMultiSelectTreeView" eSuperTypes="#//UIMLookup"/>
  <eClassifiers xsi:type="ecore:EClass" name="UIMMultiSelectListBox" eSuperTypes="#//UIMLookup"/>
  <eClassifiers xsi:type="ecore:EClass" name="UIMMultiSelectPopupSearch" eSuperTypes="#//UIMLookup"/>
  <eClassifiers xsi:type="ecore:EClass" name="UIMSingleSelectPopupSearch" eSuperTypes="#//UIMLookup"/>
  <eClassifiers xsi:type="ecore:EClass" name="UIMToggleButton" eSuperTypes="#//UIMControl"/>
  <eClassifiers xsi:type="ecore:EClass" name="UIMNumberScroller" eSuperTypes="#//UIMControl"/>
  <eClassifiers xsi:type="ecore:EClass" name="UmlReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="umlElementUid" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
