/*******************************************************************************
 * No CopyrightText Defined in the configurator file.
 ******************************************************************************/
package org.opeum.bpmn2.modeleditor.providers;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.dd.dc.util.DcAdapterFactory;
import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.topcased.modeler.providers.ILabelFeatureProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers. The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}. The adapters also support Eclipse property sheets. Note that most of the adapters are shared among multiple instances.
 * 
 * @generated
 */
public class DcModelerProviderAdapterFactory extends DcAdapterFactory implements ComposeableAdapterFactory,IChangeNotifier,IDisposable{
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * 
	 * @generated
	 */
	private ComposedAdapterFactory parentAdapterFactory;
	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * 
	 * @generated
	 */
	private IChangeNotifier changeNotifier = new ChangeNotifier();
	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * 
	 * @generated
	 */
	private Collection supportedTypes = new ArrayList();
	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.dd.dc.DocumentRoot} instances.
	 * 
	 * @generated
	 */
	private DocumentRootModelerProvider documentrootModelerProvider;
	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.dd.dc.Bounds} instances.
	 * 
	 * @generated
	 */
	private BoundsModelerProvider boundsModelerProvider;
	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.dd.dc.Font} instances.
	 * 
	 * @generated
	 */
	private FontModelerProvider fontModelerProvider;
	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.dd.dc.Point} instances.
	 * 
	 * @generated
	 */
	private PointModelerProvider pointModelerProvider;
	/**
	 * This constructs an instance.
	 * 
	 * @generated
	 */
	public DcModelerProviderAdapterFactory(){
		supportedTypes.add(ILabelFeatureProvider.class);
	}
	/**
	 * This returns the root adapter factory that contains this factory.
	 *
	 * @return the root AdapterFactory
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory(){
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}
	/**
	 * This sets the composed adapter factory that contains this factory.
	 *
	 * @param parentAdapterFactory the new parent adapter factory
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory){
		this.parentAdapterFactory = parentAdapterFactory;
	}
	/**
	 * @param type the type to test
	 * @return true if supported
	 * 
	 * @generated
	 */
	public boolean isFactoryForType(Object type){
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}
	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 *
	 * @param notifier the notifier
	 * @param type the object to adapt
	 * @return the Adapter the created adatper
	 * @generated
	 */
	public Adapter adapt(Notifier notifier,Object type){
		return super.adapt(notifier, this);
	}
	/**
	 * @param object the object to adapt
	 * @param type the type to adapt
	 * @return the adapted Object
	 * @generated
	 */
	public Object adapt(Object object,Object type){
		if(isFactoryForType(type)){
			Object adapter = super.adapt(object, type);
			if(!(type instanceof Class) || (((Class) type).isInstance(adapter))){
				return adapter;
			}
		}
		return null;
	}
	/**
	 * This adds a listener.
	 *
	 * @param notifyChangedListener the listener to add
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener){
		changeNotifier.addListener(notifyChangedListener);
	}
	/**
	 * This removes a listener.
	 *
	 * @param notifyChangedListener the listener to remove
	 * 
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener){
		changeNotifier.removeListener(notifyChangedListener);
	}
	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 *
	 * @param notification the notification to fire
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification){
		changeNotifier.fireNotifyChanged(notification);
		if(parentAdapterFactory != null){
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}
	/**
	 * This creates an adapter for a {@link org.eclipse.dd.dc.DocumentRoot}.
	 *
	 * @return the Adapter
	 * @generated
	 */
	public Adapter createDocumentRootAdapter(){
		if(documentrootModelerProvider == null){
			documentrootModelerProvider = new DocumentRootModelerProvider(this);
		}
		return documentrootModelerProvider;
	}
	/**
	 * This creates an adapter for a {@link org.eclipse.dd.dc.Bounds}.
	 *
	 * @return the Adapter
	 * @generated
	 */
	public Adapter createBoundsAdapter(){
		if(boundsModelerProvider == null){
			boundsModelerProvider = new BoundsModelerProvider(this);
		}
		return boundsModelerProvider;
	}
	/**
	 * This creates an adapter for a {@link org.eclipse.dd.dc.Font}.
	 *
	 * @return the Adapter
	 * @generated
	 */
	public Adapter createFontAdapter(){
		if(fontModelerProvider == null){
			fontModelerProvider = new FontModelerProvider(this);
		}
		return fontModelerProvider;
	}
	/**
	 * This creates an adapter for a {@link org.eclipse.dd.dc.Point}.
	 *
	 * @return the Adapter
	 * @generated
	 */
	public Adapter createPointAdapter(){
		if(pointModelerProvider == null){
			pointModelerProvider = new PointModelerProvider(this);
		}
		return pointModelerProvider;
	}
	/**
	 * This disposes all of the item providers created by this factory.
	 * 
	 * @generated
	 */
	public void dispose(){
		if(documentrootModelerProvider != null){
			documentrootModelerProvider.dispose();
		}
		if(boundsModelerProvider != null){
			boundsModelerProvider.dispose();
		}
		if(fontModelerProvider != null){
			fontModelerProvider.dispose();
		}
		if(pointModelerProvider != null){
			pointModelerProvider.dispose();
		}
	}
}
