<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simulation" nsURI="http://simulation/1.0" nsPrefix="simulation">
  <eClassifiers xsi:type="ecore:EClass" name="ValueSimulation" eSuperTypes="UML.ecore#//ValueSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="NormalDistribution" eSuperTypes="#//NumericValueDistribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mean" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="standardDeviation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UniformDistribution" eSuperTypes="#//NumericValueDistribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerLimit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperLimit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExponentialDistribution" eSuperTypes="#//NumericValueDistribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mean" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimulatedSlot" eSuperTypes="UML.ecore#//Slot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sizeDistribution" eType="#//NumericValueDistribution"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="ecore:EClass UML.ecore#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumericValueDistribution" eSuperTypes="#//ValueSimulation"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnumLiteralSimulation" eSuperTypes="#//ValueSimulation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="literal" eType="ecore:EClass UML.ecore#//EnumerationLiteral"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainedInstanceValueSimulation" eSuperTypes="#//ValueSimulation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="ecore:EClass UML.ecore#//InstanceSpecification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedInstance" eType="#//ActualInstanceSimulation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanValueSimulation" eSuperTypes="#//ValueSimulation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"
        defaultValueLiteral="0.5"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberRangeDistribution" eSuperTypes="#//NumericValueDistribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferencedInstanceSimulation" eSuperTypes="#//ValueSimulation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" eType="#//ActualInstanceSimulation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringValueSimulation" eSuperTypes="#//ValueSimulation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"
        defaultValueLiteral="0.5"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimulationModel" eSuperTypes="UML.ecore#//Package"/>
  <eClassifiers xsi:type="ecore:EClass" name="AllInstanceSimulation" eSuperTypes="UML.ecore#//InstanceSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActualInstanceSimulation" eSuperTypes="UML.ecore#//InstanceSpecification"/>
  <eClassifiers xsi:type="ecore:EEnum" name="SimulationStrategy">
    <eLiterals name="givenValue"/>
    <eLiterals name="weightedDistribution" value="1"/>
    <eLiterals name="normalDistribution" value="2"/>
    <eLiterals name="uniformDistribution" value="3"/>
    <eLiterals name="allInstanceSimulation" value="4"/>
  </eClassifiers>
</ecore:EPackage>
