<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uim" nsURI="http://opaeum.org/uimetamodel/1.0" nsPrefix="uim">
  <eClassifiers xsi:type="ecore:EClass" name="UserInteractionElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="underUserControl" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UmlReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="umlElementUid" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserInterfaceRoot" eSuperTypes="#//UserInteractionElement #//LabeledElement">
    <eOperations name="getPages" upperBound="-1" eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editability" eType="#//constraint/RootUserInteractionConstraint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="visibility" eType="#//constraint/RootUserInteractionConstraint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ignoredElements" upperBound="-1"
        eType="#//IgnoredElement" containment="true" eOpposite="#//IgnoredElement/userInterfaceRoot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superUserInterfaces" upperBound="-1"
        eType="#//UserInterfaceRoot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pageOrdering" upperBound="-1"
        eType="#//PageOrdering" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Page" eSuperTypes="#//constraint/EditableConstrainedObject #//LabeledElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="panel" lowerBound="1" eType="#//panel/AbstractPanel"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Labels" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="LabeledElement" eSuperTypes="#//UserInteractionElement #//UmlReference #//LabelContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="IgnoredElement" eSuperTypes="#//UmlReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="userInterfaceRoot" eType="#//UserInterfaceRoot"
        eOpposite="#//UserInterfaceRoot/ignoredElements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PageOrdering" eSuperTypes="#//LabeledElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="page" eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabelContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelOverride" eType="#//Labels"
        containment="true"/>
  </eClassifiers>
  <eSubpackages name="control" nsURI="http://opaeum.org/uimetamodel/control/1.0" nsPrefix="ctl">
    <eClassifiers xsi:type="ecore:EClass" name="UimNumberScroller" eSuperTypes="#//control/UimControl"/>
    <eClassifiers xsi:type="ecore:EClass" name="UimToggleButton" eSuperTypes="#//control/UimControl"/>
    <eClassifiers xsi:type="ecore:EClass" name="UimPopupSearch" eSuperTypes="#//control/UimLookup"/>
    <eClassifiers xsi:type="ecore:EClass" name="UimDropdown" eSuperTypes="#//control/UimLookup"/>
    <eClassifiers xsi:type="ecore:EClass" name="UimCheckBox" eSuperTypes="#//control/UimControl"/>
    <eClassifiers xsi:type="ecore:EClass" name="UimLookup" eSuperTypes="#//control/UimControl">
      <eStructuralFeatures xsi:type="ecore:EReference" name="lookupSource" eType="#//binding/LookupBinding"
          containment="true" eOpposite="#//binding/LookupBinding/lookup"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UimTextArea" eSuperTypes="#//control/UimControl">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rows" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EIntegerObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UimText" eSuperTypes="#//control/UimControl"/>
    <eClassifiers xsi:type="ecore:EClass" name="UimDatePopup" eSuperTypes="#//control/UimControl"/>
    <eClassifiers xsi:type="ecore:EClass" name="UimListBox" eSuperTypes="#//control/UimLookup">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rows" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EIntegerObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UimControl">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mimumWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="#//component/UimField"
          eOpposite="#//component/UimField/control"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumHeight" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EIntegerObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ControlKind">
      <eLiterals name="datePopup"/>
      <eLiterals name="dropdown" value="1"/>
      <eLiterals name="text" value="2">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Displays a single line text input field"/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="textArea" value="3">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Displays a multiline text area"/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="listBox" value="4"/>
      <eLiterals name="checkBox" value="5"/>
      <eLiterals name="numberScroller" value="6"/>
      <eLiterals name="treeView" value="7"/>
      <eLiterals name="popupSearch" value="8"/>
      <eLiterals name="toggleButton" value="9"/>
      <eLiterals name="selectionTable" value="10" literal="selectionTable"/>
      <eLiterals name="link" value="11"/>
      <eLiterals name="radioButton" value="12" literal="radioButton"/>
      <eLiterals name="label" value="13" literal="label"/>
      <eLiterals name="dateScroller" value="14" literal="dateScroller"/>
      <eLiterals name="dateTimePopup" value="15" literal="dateTimePopup"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UimTreeView" eSuperTypes="#//control/UimLookup"/>
    <eClassifiers xsi:type="ecore:EClass" name="UimLinkControl" eSuperTypes="#//control/UimControl">
      <eStructuralFeatures xsi:type="ecore:EReference" name="editorToOpen" eType="#//editor/ObjectEditor"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UimDateScroller" eSuperTypes="#//control/UimControl"/>
    <eClassifiers xsi:type="ecore:EClass" name="UimSelectionTable" eSuperTypes="#//control/UimControl"/>
    <eClassifiers xsi:type="ecore:EClass" name="UimRadioButton" eSuperTypes="#//control/UimControl"/>
    <eClassifiers xsi:type="ecore:EClass" name="UimLabel" eSuperTypes="#//control/UimControl"/>
    <eClassifiers xsi:type="ecore:EClass" name="UimDateTimePopup" eSuperTypes="#//control/UimControl"/>
  </eSubpackages>
  <eSubpackages name="editor" nsURI="http://opaeum.org/uimetamodel/editor/1.0" nsPrefix="editor">
    <eClassifiers xsi:type="ecore:EClass" name="AbstractEditor" eSuperTypes="#//UserInterfaceRoot">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pages" upperBound="-1"
          eType="#//editor/EditorPage" containment="true" eOpposite="#//editor/EditorPage/editor"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="actionBar" eType="#//editor/ActionBar"
          containment="true" eOpposite="#//editor/ActionBar/editor"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InstanceEditor" abstract="true" eSuperTypes="#//editor/AbstractEditor">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="mixed"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A ClassForm gives the user access to all the attributes and operations of ANY of the following types of classes:&#xD;&#xA;1. OrgUNit&#xD;&#xA;2. Role&#xD;&#xA;3. Normal Entity&#xD;&#xA;4. Process&#xD;&#xA;5. StateMachine"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="menuConfiguration" eType="#//editor/MenuConfiguration"
          containment="true" eOpposite="#//editor/MenuConfiguration/editor"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BehaviorExecutionEditor" eSuperTypes="#//editor/InstanceEditor">
      <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//model/BehaviorUserInteractionModel"
          eOpposite="#//model/BehaviorUserInteractionModel/editor"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EditorPage" eSuperTypes="#//Page">
      <eStructuralFeatures xsi:type="ecore:EReference" name="editor" lowerBound="1"
          eType="#//editor/AbstractEditor" eOpposite="#//editor/AbstractEditor/pages"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActionBar" eSuperTypes="#//panel/AbstractPanel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="editor" eType="#//editor/AbstractEditor"
          eOpposite="#//editor/AbstractEditor/actionBar"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MenuConfiguration" eSuperTypes="#//UserInteractionElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="editor" lowerBound="1"
          eType="#//editor/InstanceEditor" eOpposite="#//editor/InstanceEditor/menuConfiguration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
          eType="#//editor/OperationMenuItem" containment="true" eOpposite="#//editor/OperationMenuItem/menuConfiguration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationMenuItem" eSuperTypes="#//constraint/UserInteractionConstraint #//LabeledElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="menuConfiguration" lowerBound="1"
          eType="#//editor/MenuConfiguration" eOpposite="#//editor/MenuConfiguration/operations"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hidden" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResponsibilityViewer" eSuperTypes="#//editor/AbstractEditor">
      <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//model/ResponsibilityUserInteractionModel"
          eOpposite="#//model/ResponsibilityUserInteractionModel/viewer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QueryResultPage" eSuperTypes="#//Page"/>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectEditor" eSuperTypes="#//editor/InstanceEditor">
      <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//model/ClassUserInteractionModel"
          eOpposite="#//model/ClassUserInteractionModel/primaryEditor"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="binding" nsURI="http://opaeum.org/uimetamodel/binding/1.0" nsPrefix="bind">
    <eClassifiers xsi:type="ecore:EClass" name="LookupBinding" eSuperTypes="#//binding/UimBinding">
      <eStructuralFeatures xsi:type="ecore:EReference" name="lookup" eType="#//control/UimLookup"
          eOpposite="#//control/UimLookup/lookupSource"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TableBinding" eSuperTypes="#//binding/UimBinding">
      <eStructuralFeatures xsi:type="ecore:EReference" name="table" lowerBound="1"
          eType="#//component/UimDataTable" eOpposite="#//component/UimDataTable/binding"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FieldBinding" eSuperTypes="#//binding/UimBinding">
      <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="#//component/UimField"
          eOpposite="#//component/UimField/binding"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UimBinding" abstract="true" eSuperTypes="#//UmlReference">
      <eOperations name="getLastPropertyUuid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//binding/PropertyRef"
          containment="true" eOpposite="#//binding/PropertyRef/binding"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyRef" eSuperTypes="#//UmlReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="binding" eType="#//binding/UimBinding"
          eOpposite="#//binding/UimBinding/next"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="previous" eType="#//binding/PropertyRef"
          eOpposite="#//binding/PropertyRef/next"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//binding/PropertyRef"
          containment="true" eOpposite="#//binding/PropertyRef/previous"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="constraint" nsURI="http://opaeum.org/uimetamodel/security/1.0"
      nsPrefix="constr">
    <eClassifiers xsi:type="ecore:EClass" name="EditableConstrainedObject" eSuperTypes="#//constraint/ConstrainedObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="editability" eType="#//constraint/UserInteractionConstraint"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConstrainedObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="visibility" eType="#//constraint/UserInteractionConstraint"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RequiredRole" eSuperTypes="#//UmlReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" lowerBound="1"
          eType="#//constraint/RootUserInteractionConstraint" eOpposite="#//constraint/RootUserInteractionConstraint/requiredRoles"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RootUserInteractionConstraint">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiresGroupOwnership"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiresOwnership" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredRoles" upperBound="-1"
          eType="#//constraint/RequiredRole" containment="true" eOpposite="#//constraint/RequiredRole/constraint"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="openToPublic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredStates" upperBound="-1"
          eType="#//constraint/RequiredState" containment="true" eOpposite="#//constraint/RequiredState/constraint"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UserInteractionConstraint" eSuperTypes="#//constraint/RootUserInteractionConstraint">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="inheritFromParent" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
          defaultValueLiteral="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RequiredState" eSuperTypes="#//UmlReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" lowerBound="1"
          eType="#//constraint/RootUserInteractionConstraint" eOpposite="#//constraint/RootUserInteractionConstraint/requiredStates"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="action" nsURI="http://opaeum.org/uimetamodel/action/1.0" nsPrefix="action">
    <eClassifiers xsi:type="ecore:EClass" name="BuiltInActionButton" eSuperTypes="#//action/AbstractActionButton">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//action/ActionKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="labels" eType="#//Labels"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractActionButton" abstract="true"
        eSuperTypes="#//component/UimComponent #//panel/Outlayable">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A User Action is an abstract superclass for all actions a user can take on a form, typically represented as a button."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ActionKind">
      <eLiterals name="update" literal="save"/>
      <eLiterals name="delete" value="1"/>
      <eLiterals name="execute" value="3"/>
      <eLiterals name="delegateTask" value="4" literal="delegateTask"/>
      <eLiterals name="completeTask" value="5"/>
      <eLiterals name="suspend" value="6" literal="suspend"/>
      <eLiterals name="forwardTask" value="8"/>
      <eLiterals name="claimTask" value="9"/>
      <eLiterals name="add" value="2"/>
      <eLiterals name="refresh" value="7"/>
      <eLiterals name="revert" value="10"/>
      <eLiterals name="abort" value="11"/>
      <eLiterals name="skip" value="12"/>
      <eLiterals name="resume" value="13" literal=""/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TransitionButton" eSuperTypes="#//action/AbstractActionButton #//LabeledElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A slightly less form approach is to allow the user to select which transition to take on submitting the form, in stead of letting the execution of an event cause the transition"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LinkToQuery" eSuperTypes="#//action/AbstractLink #//LabeledElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An operationNavigation is typically rendered as a menu item of some sort, and takes the user to an operationUserInteraction"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InvocationButton" eSuperTypes="#//action/AbstractActionButton #//LabeledElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An operation action is typically represented as a button and executes a parameterless operation. Most often used to transition in statemachines. It is made available as a single-click button action which allows the user to execute the operation without navigating to an input form, as would be the case with a OperationNavigation"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="popup" eType="#//UserInterfaceRoot"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractLink" abstract="true" eSuperTypes="#//component/UimComponent #//panel/Outlayable">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Abstract superclass for elements that can be navigated to, typically by means of a menu item"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BuiltInLink" eSuperTypes="#//action/AbstractLink">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//action/BuiltInLinkKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="labels" eType="#//Labels"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="BuiltInLinkKind">
      <eLiterals name="auditTrail"/>
      <eLiterals name="businessIntelligence" value="1"/>
      <eLiterals name="edit" value="2" literal="edit"/>
      <eLiterals name="view" value="3" literal="view"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="panel" nsURI="http://opaeum.org/uimetamodel/panel/1.0" nsPrefix="panel">
    <eClassifiers xsi:type="ecore:EClass" name="GridPanel" eSuperTypes="#//panel/CollapsiblePanel">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfColumns" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EIntegerObject"
          defaultValueLiteral=""/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VerticalPanel" eSuperTypes="#//panel/CollapsiblePanel"/>
    <eClassifiers xsi:type="ecore:EClass" name="HorizontalPanel" eSuperTypes="#//panel/CollapsiblePanel"/>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractPanel" abstract="true" eSuperTypes="#//component/UimContainer #//LabeledElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="CollapsiblePanel" abstract="true"
        eSuperTypes="#//panel/AbstractPanel #//panel/Outlayable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isCollapsible" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBooleanObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Outlayable" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="preferredWidth" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EIntegerObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="preferredHeight" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EIntegerObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillHorizontally" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillVertically" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBooleanObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Orientation">
      <eLiterals name="horizontal"/>
      <eLiterals name="vertical" value="1"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="wizard" nsURI="http://opaeum.org/uimetamodel/wizard/1.0" nsPrefix="wizard">
    <eClassifiers xsi:type="ecore:EClass" name="AbstractWizard" abstract="true" eSuperTypes="#//UserInterfaceRoot">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pages" upperBound="-1"
          eType="#//wizard/WizardPage" containment="true" eOpposite="#//wizard/WizardPage/wizard"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NewObjectWizard" eSuperTypes="#//wizard/AbstractWizard">
      <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//model/ClassUserInteractionModel"
          eOpposite="#//model/ClassUserInteractionModel/newObjectWizard"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InvocationWizard" abstract="true"
        eSuperTypes="#//wizard/AbstractWizard"/>
    <eClassifiers xsi:type="ecore:EClass" name="WizardPage" eSuperTypes="#//Page">
      <eStructuralFeatures xsi:type="ecore:EReference" name="wizard" eType="#//wizard/AbstractWizard"
          eOpposite="#//wizard/AbstractWizard/pages"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResponsibilityInvocationWizard" eSuperTypes="#//wizard/InvocationWizard">
      <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//model/ResponsibilityUserInteractionModel"
          eOpposite="#//model/ResponsibilityUserInteractionModel/invocationWizard"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BehaviorInvocationWizard" eSuperTypes="#//wizard/InvocationWizard">
      <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//model/BehaviorUserInteractionModel"
          eOpposite="#//model/BehaviorUserInteractionModel/invocationWizard"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationResultPage" eSuperTypes="#//Page">
      <eStructuralFeatures xsi:type="ecore:EReference" name="wizard" eType="#//model/OperationInvocationWizard"
          eOpposite="#//model/OperationInvocationWizard/resultPage"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="perspective" nsURI="http://opaeum.org/uimetamodel/perspective/1.0"
      nsPrefix="persp">
    <eClassifiers xsi:type="ecore:EClass" name="PerspectiveConfiguration" eSuperTypes="#//UserInteractionElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="explorer" eType="#//perspective/NavigatorConfiguration"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="editor" eType="#//perspective/EditorConfiguration"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" eType="#//perspective/PropertiesConfiguration"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inbox" eType="#//perspective/InboxConfiguration"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outbox" eType="#//perspective/OutboxConfiguration"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ViewAllocation" abstract="true" eSuperTypes="#//UserInteractionElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EIntegerObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="#//perspective/PositionInPerspective"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="PositionInPerspective">
      <eLiterals name="left"/>
      <eLiterals name="right" value="1"/>
      <eLiterals name="top" value="2"/>
      <eLiterals name="bottom" value="3"/>
      <eLiterals name="rightTop" value="4"/>
      <eLiterals name="rightBottom" value="5"/>
      <eLiterals name="leftTop" value="6"/>
      <eLiterals name="leftBottom" value="7"/>
      <eLiterals name="topRight" value="8"/>
      <eLiterals name="topLeft" value="9"/>
      <eLiterals name="bottomRight" value="10"/>
      <eLiterals name="bottomLeft" value="11"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NavigatorConfiguration" eSuperTypes="#//perspective/ViewAllocation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
          eType="#//perspective/ClassNavigationConstraint" containment="true" eOpposite="#//perspective/ClassNavigationConstraint/explorerConfiguration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ClassNavigationConstraint" eSuperTypes="#//perspective/NavigationConstraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="explorerConfiguration"
          lowerBound="1" eType="#//perspective/NavigatorConfiguration" eOpposite="#//perspective/NavigatorConfiguration/classes"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
          eType="#//perspective/PropertyNavigationConstraint" containment="true" eOpposite="#//perspective/PropertyNavigationConstraint/owner"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="behaviors" upperBound="-1"
          eType="#//perspective/BehaviorNavigationConstraint" containment="true" eOpposite="#//perspective/BehaviorNavigationConstraint/owner"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
          eType="#//perspective/OperationNavigationConstraint" containment="true"
          eOpposite="#//perspective/OperationNavigationConstraint/owner"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyNavigationConstraint" eSuperTypes="#//perspective/NavigationConstraint #//perspective/MultiplicityElementNavigationConstraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//perspective/ClassNavigationConstraint"
          eOpposite="#//perspective/ClassNavigationConstraint/properties"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EditorConfiguration" eSuperTypes="#//perspective/ViewAllocation"/>
    <eClassifiers xsi:type="ecore:EClass" name="PropertiesConfiguration" eSuperTypes="#//perspective/ViewAllocation"/>
    <eClassifiers xsi:type="ecore:EClass" name="NavigationConstraint" eSuperTypes="#//constraint/UserInteractionConstraint #//LabeledElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hidden" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationNavigationConstraint" eSuperTypes="#//perspective/NavigationConstraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//perspective/ClassNavigationConstraint"
          eOpposite="#//perspective/ClassNavigationConstraint/operations"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="invocationConstraint"
          eType="#//perspective/NavigationConstraint" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//perspective/ParameterNavigationConstraint" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BehaviorNavigationConstraint" eSuperTypes="#//perspective/NavigationConstraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="invocationConstraint"
          eType="#//perspective/NavigationConstraint" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//perspective/ClassNavigationConstraint"
          eOpposite="#//perspective/ClassNavigationConstraint/behaviors"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//perspective/ParameterNavigationConstraint" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InboxConfiguration" eSuperTypes="#//perspective/ViewAllocation"/>
    <eClassifiers xsi:type="ecore:EClass" name="OutboxConfiguration" eSuperTypes="#//perspective/ViewAllocation"/>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterNavigationConstraint" eSuperTypes="#//perspective/MultiplicityElementNavigationConstraint"/>
    <eClassifiers xsi:type="ecore:EClass" name="MultiplicityElementNavigationConstraint"
        eSuperTypes="#//perspective/NavigationConstraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="removeConstraint" eType="#//perspective/NavigationConstraint"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="addConstraint" eType="#//perspective/NavigationConstraint"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="cube" nsURI="http://opaeum.org/uimetamodel/cube/1.0" nsPrefix="cube">
    <eClassifiers xsi:type="ecore:EClass" name="CubeQuery" eSuperTypes="#//Page">
      <eStructuralFeatures xsi:type="ecore:EReference" name="columnAxis" upperBound="-1"
          eType="#//cube/ColumnAxisEntry" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rowAxis" upperBound="-1"
          eType="#//cube/RowAxisEntry" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="measures" upperBound="-1"
          eType="#//cube/MeasureProperty" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AxisEntry" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dimensionBinding" eType="#//cube/DimensionBinding"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="levelProperty" upperBound="-1"
          eType="#//cube/LevelProperty" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DimensionBinding" eSuperTypes="#//binding/UimBinding">
      <eOperations name="toString" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eOperations name="equals" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean">
        <eParameters name="o" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
      <eOperations name="hashCode" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LevelProperty" eSuperTypes="#//LabeledElement #//UmlReference"/>
    <eClassifiers xsi:type="ecore:EClass" name="RowAxisEntry" eSuperTypes="#//cube/AxisEntry"/>
    <eClassifiers xsi:type="ecore:EClass" name="ColumnAxisEntry" eSuperTypes="#//cube/AxisEntry"/>
    <eClassifiers xsi:type="ecore:EEnum" name="AggregationFormula">
      <eLiterals name="SUM"/>
      <eLiterals name="AVERAGE" value="1"/>
      <eLiterals name="COUNT" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MeasureProperty" eSuperTypes="#//UmlReference">
      <eOperations name="equals" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean">
        <eParameters name="o" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
      </eOperations>
      <eOperations name="hashCode" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
      <eOperations name="toString" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregationFormula" eType="#//cube/AggregationFormula"
          defaultValueLiteral="null"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CubeQueryEditor" eSuperTypes="#//UmlReference #//UserInterfaceRoot">
      <eStructuralFeatures xsi:type="ecore:EReference" name="queries" upperBound="-1"
          eType="#//cube/CubeQuery" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="model" nsURI="http://opaeum.org/uimetamodel/model/1.0" nsPrefix="model">
    <eClassifiers xsi:type="ecore:EClass" name="ClassUserInteractionModel" eSuperTypes="#//model/AbstractUserInteractionModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="primaryEditor" lowerBound="1"
          eType="#//editor/ObjectEditor" containment="true" eOpposite="#//editor/ObjectEditor/model"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="secondaryEditors" upperBound="-1"
          eType="#//editor/ObjectEditor" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="newObjectWizard" lowerBound="1"
          eType="#//wizard/NewObjectWizard" containment="true" eOpposite="#//wizard/NewObjectWizard/model"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cubeQueryEditor" eType="#//cube/CubeQueryEditor"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResponsibilityUserInteractionModel"
        eSuperTypes="#//model/AbstractUserInteractionModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="invocationWizard" lowerBound="1"
          eType="#//wizard/ResponsibilityInvocationWizard" containment="true" eOpposite="#//wizard/ResponsibilityInvocationWizard/model"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="viewer" lowerBound="1"
          eType="#//editor/ResponsibilityViewer" containment="true" eOpposite="#//editor/ResponsibilityViewer/model"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractUserInteractionModel" abstract="true"
        interface="true" eSuperTypes="#//UmlReference #//UserInteractionElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="linkedUmlResource" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
          defaultValueLiteral=""/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BehaviorUserInteractionModel" eSuperTypes="#//model/AbstractUserInteractionModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="invocationWizard" eType="#//wizard/BehaviorInvocationWizard"
          containment="true" eOpposite="#//wizard/BehaviorInvocationWizard/model"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="editor" eType="#//editor/BehaviorExecutionEditor"
          containment="true" eOpposite="#//editor/BehaviorExecutionEditor/model"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QueryInvoker" eSuperTypes="#//editor/AbstractEditor #//model/AbstractUserInteractionModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="resultPage" eType="#//editor/QueryResultPage"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationInvocationWizard" eSuperTypes="#//wizard/InvocationWizard #//model/AbstractUserInteractionModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="resultPage" eType="#//wizard/OperationResultPage"
          containment="true" eOpposite="#//wizard/OperationResultPage/wizard"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EmbeddedTaskEditor" eSuperTypes="#//editor/AbstractEditor #//model/AbstractUserInteractionModel"/>
  </eSubpackages>
  <eSubpackages name="component" nsURI="http://opaeum.org/uimetamodel/component/1.0"
      nsPrefix="comp">
    <eClassifiers xsi:type="ecore:EClass" name="UimField" eSuperTypes="#//constraint/EditableConstrainedObject #//component/UimComponent #//panel/Outlayable">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A User Field is an abstract superclass for all fields a user can view and/or update on a form, typically represented as some kind of input/output form field."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="control" lowerBound="1"
          eType="#//control/UimControl" containment="true" eOpposite="#//control/UimControl/field"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="controlKind" eType="#//control/ControlKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumLabelWidth" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EIntegerObject"
          defaultValueLiteral="200"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="binding" lowerBound="1"
          eType="#//binding/FieldBinding" containment="true" eOpposite="#//binding/FieldBinding/field"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="orientation" eType="#//panel/Orientation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UimComponent" abstract="true" eSuperTypes="#//UserInteractionElement #//constraint/ConstrainedObject #//LabelContainer">
      <eOperations name="getParent" eType="#//component/UimContainer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UimDataTable" eSuperTypes="#//component/MasterComponent #//component/UimContainer #//panel/Outlayable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="binding" eType="#//binding/TableBinding"
          containment="true" eOpposite="#//binding/TableBinding/table"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="actionsOnMultipleSelection"
          upperBound="-1" eType="#//action/AbstractActionButton" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UimContainer" abstract="true" eSuperTypes="#//component/UimComponent #//constraint/EditableConstrainedObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
          eType="#//component/UimComponent" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MasterComponent" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="detailComponents" upperBound="-1"
          eType="#//component/DetailComponent" eOpposite="#//component/DetailComponent/masterComponent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MasterTree" eSuperTypes="#//component/MasterComponent"/>
    <eClassifiers xsi:type="ecore:EClass" name="DetailComponent" eSuperTypes="#//component/UimComponent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="masterComponent" lowerBound="1"
          eType="#//component/MasterComponent" eOpposite="#//component/MasterComponent/detailComponents"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="panelsForClasses" upperBound="-1"
          eType="#//component/PanelForClass" containment="true" eOpposite="#//component/PanelForClass/detailComponent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PanelForClass" eSuperTypes="#//UmlReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="detailComponent" lowerBound="1"
          eType="#//component/DetailComponent" eOpposite="#//component/DetailComponent/panelsForClasses"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="panel" lowerBound="1"
          eType="#//panel/AbstractPanel"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
