package org.opaeum.textmetamodel;

public enum TextSourceFolderIdentifier implements ISourceFolderIdentifier{
	DOMAIN_GEN_RESOURCE,
	DOMAIN_TEST_RESOURCE,
	DOMAIN_GEN_TEST_RESOURCE,
	WEBAPP_RESOURCE,
	INTEGRATED_ADAPTOR_GEN_RESOURCE,
	INTEGRATED_ADAPTOR_TEST_GEN_RESOURCE,
	WEB_PROJECT_ROOT
}