package org.opaeum.metamodel.core.internal;

public class TagNames{
	public static final String IS_ROOT_ENTITY = "isRootEntity";
	public static final String DEFAULT_EMAIL_ADDRESS = "defaultEmailAddress";
	public static final String MAPPED_IMPLEMENTATION_TYPE = "mappedImplementationType";
	public static final String CODE_GENERATION_STRATEGY = "codeGenerationStrategy";
	public static final String MAPPED_IMPLEMENTATION_PACKAGE = "mappedImplementationPackage";
	public static final String IS_ROOT_PACKAGE = "isRootPackage";
	public static final String IS_SCHEMA = "isSchema";
	public static final String NAME_PROPERTY = "nameProperty";
	public static final String ROLE_IN_CUBE = "roleInCube";
	public static final String AGGREGATION_FORMULAS = "aggregationFormulas";
	public static final String DERIVATION_FORMULA = "derivationFormula";
	public static final String IS_PRIMARY_KEY = "isPrimaryKey";
	public static final String FROM_EXPRESSION = "fromExpression";
	public static final String CC_EXPRESSION = "ccExpression";
	public static final String BCC_EXPRESSION = "bccExpression";
	public static final String TEMPLATE_EXPRESSION = "templateExpression";
	public static final String REASSIGNMENT = "reassignment";
	public static final String DEADLINES = "deadlines";
	public static final String NOTIFICATIONS = "notifications";
	public static final String STAKEHOLDERS = "stakeholders";
	public static final String POTENTIAL_OWNERS = "potentialOwners";
	public static final String BUSINESS_ADMINISTRATORS = "businessAdministrators";
	public static final String TIME_OBSERVATIONS = "timeObservations";
	public static final String DURATION_OBSERVATIONS = "durationObservations";
	public static final String DURATION_BASED_COST_OBSERVATIONS = "durationBasedCostObservations";
	public static final String QUANTITY_BASED_COST_OBSERVATIONS = "quantityBasedCostObservations";
	public static final String EVALUATION_INTERVAL = "evaluationInterval";
	public static final String SELECTOR = "selector";
	public static final String BUSINESS_CALENDAR_TO_USE = "businessCalendarToUse";
	public static final String TIME_UNIT = "timeUnit";
	public static final String DEADLINE_KIND = "kind";
	public static final String DEADLINE = "deadline";
	public static final String TASK_DELEGATION = "taskDelegation";
	public static final String IS_CUMULATIVE = "isCumulative";
	public static final String MESSAGE_ARGUMENTS = "messageArguments";
	public static final String RESOURCES_PAID_FOR = "resourcesPaidFor";
	public static final String RESOURCE_PAID_FOR = "resourcePaidFor";
	public static final String CONTROLLED_BY = "controlledBy";
	public static final String QUANTITY_EXPRESSION = "quantityExpression";
	public static final String MODEL_TYPE = "modelType";
	public static final String ARTIFACT_IDENTIFIER = "artifactIdentifier";
	public static final String PERSISTENT_NAME = "persistentName";
	public static final String GENERATE_ABSTRACT_SUPERTYPE = "generateAbstractSupertype";
	public static final String AUDITING_ENABLED = "auditingEnabled";
}
