<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="nakedumlmetamodel"
    nsURI="http://nakedumlmetamodel/1.0" nsPrefix="nakedumlmetamodel">
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lifeCycle" eType="#//LifeCycle"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrganizationUnit" eSuperTypes="#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="businessProcesses" upperBound="-1"
        eType="#//BusinessProcess" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//BusinessService" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tasks" upperBound="-1"
        eType="#//StandaloneTask" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessProcess" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//EmbeddedSimpleTask" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="screenflowTasks" upperBound="-1"
        eType="#//EmbeddedScreenflowTask"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScreenFlow" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//StateMachine"/>
  <eClassifiers xsi:type="ecore:EClass" name="StandaloneTask" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementation" eType="#//ScreenFlow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmbeddedSimpleTask" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//OpaqueAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="EmbeddedScreenflowTask" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//CallBehaviorAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementation" eType="#//ScreenFlow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LifeCycle" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//StateMachine"/>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessService" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementation" eType="#//BusinessProcess"/>
  </eClassifiers>
</ecore:EPackage>
