package org.opaeum.reverse.popup.actions;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.Collection;

import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.core.runtime.Path;
import org.eclipse.jdt.core.dom.ITypeBinding;
import org.eclipse.uml2.uml.Classifier;
import org.eclipse.uml2.uml.Model;
import org.eclipse.uml2.uml.Package;
import org.opaeum.linkage.MappedTypeLoader;

public class SimpleUmlGenerator extends AbstractUmlGenerator{
	@Override
	public void generateUml(Collection<ITypeBinding> selection,Package library) throws Exception{
		if(library instanceof Model){
			IFile ifile = ResourcesPlugin.getWorkspace().getRoot().getFile(new Path(library.eResource().getURI().toPlatformString(true)));
			String absolutePath = ifile.getLocation().toFile().getAbsolutePath();
			File mappedTypesFile = new File(absolutePath.substring(0, absolutePath.length() - 3) + MappedTypeLoader.MAPPINGS_EXTENSION);
			factory = new ClassifierFactory(library);
			if(mappedTypesFile.exists()){
				factory.getMappedTypes().load(new FileInputStream(mappedTypesFile));
			}
			for(ITypeBinding t:selection){
				if(!t.isAnnotation()){
					// Only do annotations in profiles
					Classifier cls = factory.getClassifierFor(t);
					factory.getMappedTypes().put(cls.getQualifiedName(), t.getQualifiedName());
					populateAttributes(library, cls, t);
					populateOperations(library, cls, t);
				}
			}
			library.eResource().save(null);
			factory.getMappedTypes().store(new FileOutputStream(mappedTypesFile), "Generated by Opaeum");
		}
	}
}
