/**
 */
package org.opaeum.uim.action.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;
import org.opaeum.uim.action.util.ActionAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ActionItemProviderAdapterFactory extends ActionAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ActionItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opaeum.uim.action.BuiltInAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BuiltInActionItemProvider builtInActionItemProvider;

	/**
	 * This creates an adapter for a {@link org.opaeum.uim.action.BuiltInAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBuiltInActionAdapter() {
		if (builtInActionItemProvider == null) {
			builtInActionItemProvider = new BuiltInActionItemProvider(this);
		}

		return builtInActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opaeum.uim.action.TransitionAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TransitionActionItemProvider transitionActionItemProvider;

	/**
	 * This creates an adapter for a {@link org.opaeum.uim.action.TransitionAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTransitionActionAdapter() {
		if (transitionActionItemProvider == null) {
			transitionActionItemProvider = new TransitionActionItemProvider(this);
		}

		return transitionActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opaeum.uim.action.LinkToOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LinkToOperationItemProvider linkToOperationItemProvider;

	/**
	 * This creates an adapter for a {@link org.opaeum.uim.action.LinkToOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLinkToOperationAdapter() {
		if (linkToOperationItemProvider == null) {
			linkToOperationItemProvider = new LinkToOperationItemProvider(this);
		}

		return linkToOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opaeum.uim.action.OperationAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperationActionItemProvider operationActionItemProvider;

	/**
	 * This creates an adapter for a {@link org.opaeum.uim.action.OperationAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperationActionAdapter() {
		if (operationActionItemProvider == null) {
			operationActionItemProvider = new OperationActionItemProvider(this);
		}

		return operationActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opaeum.uim.action.LinkToEntity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LinkToEntityItemProvider linkToEntityItemProvider;

	/**
	 * This creates an adapter for a {@link org.opaeum.uim.action.LinkToEntity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLinkToEntityAdapter() {
		if (linkToEntityItemProvider == null) {
			linkToEntityItemProvider = new LinkToEntityItemProvider(this);
		}

		return linkToEntityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opaeum.uim.action.OperationActionPopup} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperationActionPopupItemProvider operationActionPopupItemProvider;

	/**
	 * This creates an adapter for a {@link org.opaeum.uim.action.OperationActionPopup}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperationActionPopupAdapter() {
		if (operationActionPopupItemProvider == null) {
			operationActionPopupItemProvider = new OperationActionPopupItemProvider(this);
		}

		return operationActionPopupItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.opaeum.uim.action.OperationPopupPage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperationPopupPageItemProvider operationPopupPageItemProvider;

	/**
	 * This creates an adapter for a {@link org.opaeum.uim.action.OperationPopupPage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperationPopupPageAdapter() {
		if (operationPopupPageItemProvider == null) {
			operationPopupPageItemProvider = new OperationPopupPageItemProvider(this);
		}

		return operationPopupPageItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (builtInActionItemProvider != null) builtInActionItemProvider.dispose();
		if (transitionActionItemProvider != null) transitionActionItemProvider.dispose();
		if (linkToOperationItemProvider != null) linkToOperationItemProvider.dispose();
		if (operationActionItemProvider != null) operationActionItemProvider.dispose();
		if (linkToEntityItemProvider != null) linkToEntityItemProvider.dispose();
		if (operationActionPopupItemProvider != null) operationActionPopupItemProvider.dispose();
		if (operationPopupPageItemProvider != null) operationPopupPageItemProvider.dispose();
	}

}
